name: Scrape Silicon Prices

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours (00:00, 06:00, 12:00, 18:00 UTC)
  workflow_dispatch:      # Allows you to click "Run Now" manually for testing

permissions:
  contents: write         # Critical: Allows the bot to write back to the repo

jobs:
  scrape-and-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run the Scraper
        run: python scraper.py
        
      - name: Commit and Push if changed
        run: |
          git config user.name "SiliconMeter Bot"
          git config user.email "actions@users.noreply.github.com"
          git add data.json
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
